### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [cshanerasque/prj-rev-bwfs-dasmoto#6]
https://github.com/cshanerasque/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/resources/css/style.css#L37

You shouldn't have to repeat this style in so many CSS rules. Use a single CSS rule targeting multiple elements for commonly shared styles:

```css
h1, h2, h3, p {
  font-family: Helvetica;
}
```
